import './globals.css'
import {Dosis} from 'next/font/google'

const dosis = Dosis({subsets: ['latin']})

export const metadata = {
	title: 'TodoLickIt',
	description: 'Generated by create next app',
}

export default function RootLayout({children}: {children: React.ReactNode}) {
	return (
		<html lang="en">
			<body
				className={`${dosis.className} bg-[#4C0033] text-[#ff96d0] text-3xl`}
			>
				{children}
			</body>
		</html>
	)
}
